export const LANGUAGE_SUGGESTIONS = {
  cpp: {
    keywords: [
      "#include",
      "using",
      "namespace",
      "int",
      "char",
      "float",
      "double",
      "string",
      "bool",
      "if",
      "else",
      "for",
      "while",
      "do",
      "switch",
      "case",
      "return",
      "class",
      "struct",
      "public",
      "private",
      "protected",
      "void",
      "const",
      "auto",
      "cout",
      "cin",
      "endl",
      "vector",
      "map",
      "set",
    ],
    snippets: [
      { label: "main", insertText: "int main() {\n    return 0;\n}\n", detail: "Main function." },
      { label: "for", insertText: "for (int i = 0; i < ${1:n}; i++) {\n    ${2:// body}\n}\n", detail: "For loop." },
      { label: "if", insertText: "if (${1:condition}) {\n    ${2:// body}\n}\n", detail: "If statement." },
      { label: "while", insertText: "while (${1:condition}) {\n    ${2:// body}\n}\n", detail: "While loop." },
      { label: "cout", insertText: "cout << ${1:value} << endl;\n", detail: "Print to standard output." },
      { label: "class", insertText: "class ${1:ClassName} {\npublic:\n    ${2:// members}\n};\n", detail: "Class declaration." },
    ],
  },
  python: {
    keywords: [
      "def",
      "class",
      "if",
      "elif",
      "else",
      "for",
      "while",
      "try",
      "except",
      "finally",
      "import",
      "from",
      "return",
      "yield",
      "lambda",
      "with",
      "as",
      "print",
      "input",
      "len",
      "range",
      "list",
      "dict",
      "set",
      "tuple",
    ],
    snippets: [
      { label: "def", insertText: "def ${1:name}(${2:args}):\n    ${3:// body}\n    return ${4:value}\n", detail: "Function definition." },
      { label: "if", insertText: "if ${1:condition}:\n    ${2:# body}\n", detail: "If statement." },
      { label: "for", insertText: "for ${1:item} in ${2:iterable}:\n    ${3:# body}\n", detail: "For loop." },
      { label: "while", insertText: "while ${1:condition}:\n    ${2:# body}\n", detail: "While loop." },
      { label: "class", insertText: "class ${1:ClassName}:\n    def __init__(self, ${2:args}):\n        ${3:pass}\n", detail: "Class definition." },
      { label: "main", insertText: "def main():\n    ${1:pass}\n\nif __name__ == \"__main__\":\n    main()\n", detail: "Main guard." },
    ],
  },
  javascript: {
    keywords: [
      "const",
      "let",
      "var",
      "function",
      "return",
      "if",
      "else",
      "for",
      "while",
      "switch",
      "class",
      "import",
      "export",
      "async",
      "await",
      "try",
      "catch",
      "console.log",
    ],
    snippets: [
      { label: "function", insertText: "function ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Function declaration." },
      { label: "arrow", insertText: "const ${1:name} = (${2:args}) => {\n    ${3:// body}\n};\n", detail: "Arrow function." },
      { label: "console.log", insertText: "console.log(${1:value});\n", detail: "Log to console." },
      { label: "if", insertText: "if (${1:condition}) {\n    ${2:// body}\n}\n", detail: "If statement." },
      { label: "for", insertText: "for (let i = 0; i < ${1:length}; i++) {\n    ${2:// body}\n}\n", detail: "For loop." },
      { label: "async", insertText: "async function ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Async function." },
    ],
  },
  java: {
    keywords: [
      "public",
      "private",
      "protected",
      "class",
      "static",
      "void",
      "int",
      "double",
      "String",
      "boolean",
      "if",
      "else",
      "for",
      "while",
      "switch",
      "return",
      "new",
      "extends",
      "implements",
      "interface",
      "import",
      "package",
    ],
    snippets: [
      { label: "main", insertText: "public static void main(String[] args) {\n    ${1:// code}\n}\n", detail: "Java main method." },
      { label: "class", insertText: "class ${1:ClassName} {\n    ${2:// fields and methods}\n}\n", detail: "Class definition." },
      { label: "for", insertText: "for (int i = 0; i < ${1:n}; i++) {\n    ${2:// body}\n}\n", detail: "For loop." },
      { label: "if", insertText: "if (${1:condition}) {\n    ${2:// body}\n}\n", detail: "If statement." },
      { label: "try/catch", insertText: "try {\n    ${1:// code}\n} catch (Exception e) {\n    ${2:// handle}\n}\n", detail: "Try/catch block." },
    ],
  },
  c: {
    keywords: [
      "#include",
      "#define",
      "int",
      "char",
      "float",
      "double",
      "void",
      "struct",
      "if",
      "else",
      "for",
      "while",
      "switch",
      "case",
      "return",
      "sizeof",
      "printf",
      "scanf",
    ],
    snippets: [
      { label: "main", insertText: "int main() {\n    ${1:// code}\n    return 0;\n}\n", detail: "C main function." },
      { label: "printf", insertText: "printf(\"${1:message}\\n\");\n", detail: "Print formatted output." },
      { label: "scanf", insertText: "scanf(\"${1:%d}\", &${2:value});\n", detail: "Read input." },
      { label: "for", insertText: "for (int i = 0; i < ${1:n}; i++) {\n    ${2:// body}\n}\n", detail: "For loop." },
      { label: "if", insertText: "if (${1:condition}) {\n    ${2:// body}\n}\n", detail: "If statement." },
    ],
  },
  go: {
    keywords: [
      "package",
      "import",
      "func",
      "var",
      "const",
      "type",
      "struct",
      "interface",
      "if",
      "else",
      "for",
      "range",
      "switch",
      "case",
      "return",
      "go",
      "defer",
      "chan",
      "map",
    ],
    snippets: [
      { label: "main", insertText: "func main() {\n    ${1:// code}\n}\n", detail: "Main function." },
      { label: "func", insertText: "func ${1:name}(${2:args}) ${3:returnType} {\n    ${4:// body}\n}\n", detail: "Function definition." },
      { label: "for", insertText: "for ${1:i} := 0; ${1:i} < ${2:n}; ${1:i}++ {\n    ${3:// body}\n}\n", detail: "For loop." },
      { label: "if", insertText: "if ${1:condition} {\n    ${2:// body}\n}\n", detail: "If statement." },
    ],
  },
  rust: {
    keywords: [
      "fn",
      "let",
      "mut",
      "const",
      "struct",
      "enum",
      "impl",
      "trait",
      "match",
      "if",
      "else",
      "loop",
      "while",
      "for",
      "return",
      "use",
      "mod",
      "pub",
      "self",
      "Self",
      "println!",
      "print!",
      "vec!",
    ],
    snippets: [
      { label: "main", insertText: "fn main() {\n    ${1:// code}\n}\n", detail: "Main function." },
      { label: "fn", insertText: "fn ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Function definition." },
      { label: "match", insertText: "match ${1:value} {\n    ${2:_} => ${3:// handle},\n}\n", detail: "Match expression." },
      { label: "struct", insertText: "struct ${1:Name} {\n    ${2:field}: ${3:Type},\n}\n", detail: "Struct definition." },
    ],
  },
  php: {
    keywords: [
      "<?php",
      "echo",
      "function",
      "class",
      "public",
      "private",
      "protected",
      "if",
      "else",
      "foreach",
      "for",
      "while",
      "return",
      "new",
      "require",
      "include",
    ],
    snippets: [
      { label: "function", insertText: "function ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Function definition." },
      { label: "class", insertText: "class ${1:ClassName} {\n    ${2:// properties and methods}\n}\n", detail: "Class definition." },
      { label: "foreach", insertText: "foreach (${1:$array} as ${2:$value}) {\n    ${3:// body}\n}\n", detail: "Foreach loop." },
      { label: "if", insertText: "if (${1:condition}) {\n    ${2:// body}\n}\n", detail: "If statement." },
    ],
  },
  ruby: {
    keywords: [
      "def",
      "class",
      "module",
      "if",
      "unless",
      "elsif",
      "else",
      "while",
      "until",
      "for",
      "each",
      "do",
      "end",
      "return",
      "require",
      "attr_accessor",
      "puts",
    ],
    snippets: [
      { label: "def", insertText: "def ${1:name}(${2:args})\n  ${3:# body}\nend\n", detail: "Method definition." },
      { label: "class", insertText: "class ${1:ClassName}\n  ${2:# body}\nend\n", detail: "Class definition." },
      { label: "each", insertText: "${1:items}.each do |${2:item}|\n  ${3:# body}\nend\n", detail: "Each loop." },
      { label: "if", insertText: "if ${1:condition}\n  ${2:# body}\nend\n", detail: "If statement." },
    ],
  },
  kotlin: {
    keywords: [
      "fun",
      "val",
      "var",
      "class",
      "object",
      "data",
      "interface",
      "when",
      "if",
      "else",
      "for",
      "while",
      "return",
      "null",
      "true",
      "false",
      "println",
    ],
    snippets: [
      { label: "fun", insertText: "fun ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Function definition." },
      { label: "main", insertText: "fun main() {\n    ${1:println(\"Hello\")}\n}\n", detail: "Main function." },
      { label: "class", insertText: "class ${1:ClassName} {\n    ${2:// body}\n}\n", detail: "Class definition." },
      { label: "when", insertText: "when (${1:value}) {\n    ${2:condition} -> ${3:// body}\n}\n", detail: "When expression." },
    ],
  },
  swift: {
    keywords: [
      "import",
      "let",
      "var",
      "func",
      "class",
      "struct",
      "enum",
      "protocol",
      "if",
      "else",
      "for",
      "while",
      "switch",
      "case",
      "guard",
      "return",
      "nil",
      "true",
      "false",
      "print",
    ],
    snippets: [
      { label: "func", insertText: "func ${1:name}(${2:args}) {\n    ${3:// body}\n}\n", detail: "Function definition." },
      { label: "class", insertText: "class ${1:ClassName} {\n    ${2:// body}\n}\n", detail: "Class definition." },
      { label: "struct", insertText: "struct ${1:Name} {\n    ${2:// properties}\n}\n", detail: "Struct definition." },
      { label: "if", insertText: "if ${1:condition} {\n    ${2:// body}\n}\n", detail: "If statement." },
    ],
  },
  typescript: {
    keywords: [
      "interface",
      "type",
      "class",
      "public",
      "private",
      "protected",
      "const",
      "let",
      "function",
      "async",
      "await",
      "Promise",
      "string",
      "number",
      "boolean",
      "any",
      "unknown",
      "void",
    ],
    snippets: [
      { label: "interface", insertText: "interface ${1:Name} {\n  ${2:property}: ${3:type};\n}\n", detail: "Interface definition." },
      { label: "type", insertText: "type ${1:Name} = ${2:type};\n", detail: "Type alias." },
      { label: "function", insertText: "function ${1:name}(${2:args}): ${3:returnType} {\n  ${4:// body}\n}\n", detail: "Function declaration." },
      { label: "async", insertText: "async function ${1:name}(${2:args}) {\n  ${3:// body}\n}\n", detail: "Async function." },
      { label: "arrow", insertText: "const ${1:name} = (${2:args}) => {\n  ${3:// body}\n};\n", detail: "Arrow function." },
    ],
  },
};

const DEFAULT_LANGUAGE = "javascript";

const buildItems = (language, monaco) => {
  const config = LANGUAGE_SUGGESTIONS[language] || LANGUAGE_SUGGESTIONS[DEFAULT_LANGUAGE];
  const suggestions = [];

  for (const keyword of config.keywords) {
    suggestions.push({
      label: keyword,
      kind: monaco.languages.CompletionItemKind.Keyword,
      insertText: keyword,
      detail: "Keyword",
    });
  }

  for (const snippet of config.snippets) {
    suggestions.push({
      label: snippet.label,
      kind: monaco.languages.CompletionItemKind.Snippet,
      insertText: snippet.insertText,
      insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
      detail: snippet.detail,
    });
  }

  return suggestions;
};

export const registerLanguageCompletionProvider = (monaco, language) => {
  if (!monaco || !language) return [];

  const config = LANGUAGE_SUGGESTIONS[language];
  if (!config) return [];

  const provider = {
    triggerCharacters: [".", " ", "#", "<", "s", "f", "i", "w", "m", "p"],
    provideCompletionItems(model, position) {
      const word = model.getWordUntilPosition(position);
      const prefix = word.word || "";
      const items = buildItems(language, monaco).filter((item) => {
        const candidate = String(item.label || "").toLowerCase();
        return !prefix || candidate.startsWith(prefix.toLowerCase()) || candidate.includes(prefix.toLowerCase());
      });

      return { suggestions: items };
    },
  };

  const disposable = monaco.languages.registerCompletionItemProvider(language, provider);
  return [disposable];
};
